/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#adc6ff",
        "surface-tint": "#c0c1ff",
        "surface-container": "#1e1e32",
        "on-tertiary-container": "#340080",
        "on-primary-fixed": "#07006c",
        "secondary-container": "#0566d9",
        "on-primary-container": "#0d0096",
        "tertiary-fixed-dim": "#d0bcff",
        "on-error-container": "#ffdad6",
        "outline": "#908fa0",
        "tertiary-container": "#a078ff",
        "background": "#111125",
        "primary-fixed": "#e1e0ff",
        "tertiary": "#d0bcff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary": "#002e6a",
        "on-surface": "#e2e0fc",
        "primary-container": "#8083ff",
        "on-tertiary": "#3c0091",
        "on-background": "#e2e0fc",
        "error": "#ffb4ab",
        "on-secondary-container": "#e6ecff",
        "inverse-on-surface": "#2f2e43",
        "outline-variant": "#464554",
        "inverse-surface": "#e2e0fc",
        "on-primary": "#1000a9",
        "surface-bright": "#37374d",
        "surface-container-highest": "#333348",
        "surface-variant": "#333348",
        "primary": "#c0c1ff",
        "tertiary-fixed": "#e9ddff",
        "surface-container-high": "#28283d",
        "secondary": "#adc6ff",
        "on-secondary-fixed": "#001a42",
        "error-container": "#93000a",
        "secondary-fixed": "#d8e2ff",
        "surface-container-low": "#1a1a2e",
        "inverse-primary": "#494bd6",
        "surface-container-lowest": "#0c0c1f",
        "on-secondary-fixed-variant": "#004395",
        "primary-fixed-dim": "#c0c1ff",
        "on-surface-variant": "#c7c4d7",
        "on-error": "#690005",
        "on-tertiary-fixed": "#23005c",
        "surface-dim": "#111125",
        "surface": "#111125",
        "on-tertiary-fixed-variant": "#5516be",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        xl: "64px",
        lg: "40px",
        base: "8px",
        sm: "12px",
        md: "24px",
        xs: "4px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-xl": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "title-md": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
      },
      fontSize: {
        "display-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-sm": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "label-xs": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
      animation: {
        "pulse-slow":
          "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        blob: "blob 60s infinite",
        float: "float 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out 3s infinite",
        "float-slow": "float 8s ease-in-out 1s infinite",
        "float-slow-delayed": "float 8s ease-in-out 4s infinite",
      },
      keyframes: {
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
    },
  },
  plugins: [],
};