from typing import TypedDict,Annotated
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph,START,END
from langgraph.prebuilt import ToolNode
from model import llm
from langgraph.prebuilt import tools_condition
from guardrail import validate_query


class State(TypedDict):
    query: str
    messages:Annotated[list,add_messages]
    response: str


builder = StateGraph(State)

from langchain_community.tools.tavily_search import TavilySearchResults 
tavily_api_key = "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"


web_search = TavilySearchResults(max_results=5, tavily_api_key="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")

from langgraph.prebuilt import ToolNode


tools = [web_search]

tool_node = ToolNode(tools)


llm_with_tools = llm.bind_tools(tools)




def tool_calling_llm(state :dict):
    return {"messages":[llm_with_tools.invoke(state["messages"])]}


def llm_node(query:dict)-> dict:
    response = llm.invoke(query)
    return  response



    messages = state["messages"]

    prompt = f"""
    You are a professional AI research assistant.

    Analyze the search results properly and provide:
    - Give it in a list format or in points
    -Give  5 results only  
    Search Results:
    {messages}

    Give a professional response.
    """

    response = llm.invoke(prompt)

    return {
        "messages": [response]
    }


def final_response(state: dict):

    messages = state["messages"]

    prompt = f"""
    You are an expert AI Research Agent. Your goal is to synthesize the search results into a highly professional, well-formatted, and visually appealing executive summary.

    Based on the provided search results, extract EXACTLY 5 major news points.

    STRICT RULES:
    - MUST generate exactly 5 distinct points. Do not generate less than 5.
    - DO NOT stop early. Continue until all 5 points are fully generated.
    - DO NOT summarize into a single paragraph.
    - DO NOT return raw JSON.
    - DO NOT mention the search process, "search results", or the context.
    - Use clear and beautiful Markdown formatting to make it look clean and highly readable.
    - Use appropriate emojis to add a professional touch to the structure.
    
    EXPECTED FORMAT FOR EACH POINT:
    ### 🔹 [Compelling Headline]
    *Summary:* [Provide a comprehensive 2-3 sentence explanation with rich context and key details]

    ---

    Make sure the response feels like an authoritative, polished, and beautifully structured report generated by a premium AI Assistant.

    Search Data:
    {messages}
    """

    response = llm.invoke(prompt)

    return {
        "messages": [response]
    }
def guardrail_node(state: dict):
    response = validate_query(state["query"])

    if "ALLOWED" not in response:
        return {
            "response": response
        }
    return {}

def guardrail_router(state: dict):
    if state.get("response"):
        return END
    return "llm"

builder.add_node("llm",tool_calling_llm)
builder.add_node("tools",ToolNode(tools))
builder.add_node("final_llm",final_response)
builder.add_node("guardrail",guardrail_node)



builder.add_edge(START,"guardrail")
builder.add_conditional_edges("guardrail", guardrail_router)
builder.add_conditional_edges("llm",tools_condition)
builder.add_edge("tools","final_llm")
builder.add_edge("final_llm",END)



graph = builder.compile()


