from typing import TypedDict,Annotated
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph,START,END
from langgraph.prebuilt import ToolNode
from model import llm
from langgraph.prebuilt import tools_condition
from guardrail import validate_query
from langchain_tavily import TavilySearch
from  dotenv import load_dotenv
from langsmith import traceable
import os 

os.getenv("LANGSMITH_TRACING") = True
os.getenv("LANGSMITH_ENDPOIN") = "https://api.smith.langchain.com"
os.getenv("LANGSMITH_PROJECT") = "Researcher_Agent"
 
load_dotenv()



class State(TypedDict):
    query: str
    messages:Annotated[list,add_messages]
    response: str
    images: list


builder = StateGraph(State)


web_search = TavilySearch(
    max_results=5,
    include_images=True
)

tools = [web_search]

tool_node = ToolNode(tools)

llm_with_tools = llm.bind_tools(tools)


def tool_calling_llm(state: dict):
    return {"messages": [llm_with_tools.invoke(state["messages"])]}


def image_search_node(state: dict):
    """Dedicated node to fetch related images for the query using Tavily."""
    query = state.get("query", "")
    
    try:
        search = TavilySearch(
            max_results=5,
           
            include_images=True,
            topic="news"
        )
        results = search.invoke({"query": query})
        
        # Extract image URLs from results
        images = []
        if isinstance(results, list):
            for result in results:
                if isinstance(result, dict):
                    # Check for image URLs in the result
                    url = result.get("url", "")
                    content = result.get("content", "")
                    # Look for image URLs in the content or dedicated image fields
                    if any(ext in url.lower() for ext in ['.jpg', '.jpeg', '.png', '.gif', '.webp']):
                        images.append(url)
        elif isinstance(results, dict):
            # Tavily may return images in an 'images' field
            if "images" in results:
                images = results["images"][:5]
        
        # If we got no images from above, try a direct image search
        if not images:
            img_search = TavilySearch(
                max_results=5,
               
                include_images=True,
                topic="general"
            )
            img_results = img_search.invoke({"query": f"{query} images photos"})
            
            if isinstance(img_results, dict) and "images" in img_results:
                images = img_results["images"][:5]
            elif isinstance(img_results, list):
                for r in img_results:
                    if isinstance(r, dict):
                        url = r.get("url", "")
                        if any(ext in url.lower() for ext in ['.jpg', '.jpeg', '.png', '.gif', '.webp']):
                            images.append(url)
        
        return {"images": images[:5]}
    except Exception as e:
        print(f"Image search error: {e}")
        return {"images": []}


def final_response(state: dict):

    messages = state["messages"]
    images = state.get("images", [])
    
    # Build the image context for the prompt
    image_context = ""
    if images:
        image_context = "\n\nAvailable Related Images (use these URLs in your response):\n"
        for i, img_url in enumerate(images, 1):
            image_context += f"{i}. {img_url}\n"
        image_context += "\nIMPORTANT: For each news point, include ONE related image from the list above using this exact markdown syntax: ![Related Image](URL)"

    prompt = f"""
    You are an expert AI Research Agent. Your goal is to synthesize the search results into a highly professional, well-formatted, and visually appealing executive summary.

    Based on the provided search results, extract EXACTLY 5 major news points.

    STRICT RULES:
    - MUST generate exactly 5 distinct points. Do not generate less than 5.
    - DO NOT stop early. Continue until all 5 points are fully generated.
    - DO NOT summarize into a single paragraph.
    - DO NOT return raw JSON.
    - DO NOT mention the search process, "search results", or the context.
    - Use clear and beautiful Markdown formatting to make it look clean and highly readable.
    - Use appropriate emojis to add a professional touch to the structure.
    
    EXPECTED FORMAT FOR EACH POINT:
    ### 🔹 [Compelling Headline]
    *Summary:* [Provide a comprehensive 2-3 sentence explanation with rich context and key details]

    ![Related Image](IMAGE_URL_HERE)

    ---

    Make sure the response feels like an authoritative, polished, and beautifully structured report generated by a premium AI Assistant.
    {image_context}

    Search Data:
    {messages}
    """

    response = llm.invoke(prompt)

    return {
        "messages": [response]
    }


def guardrail_node(state: dict):
    response = validate_query(state["query"])

    if "ALLOWED" not in response:
        return {
            "response": response
        }
    return {}

def guardrail_router(state: dict):
    if state.get("response"):
        return END
    return "llm"

builder.add_node("llm",tool_calling_llm)
builder.add_node("tools",ToolNode(tools))
builder.add_node("image_search", image_search_node)
builder.add_node("final_llm",final_response)
builder.add_node("guardrail",guardrail_node)



builder.add_edge(START,"guardrail")
builder.add_conditional_edges("guardrail", guardrail_router)
builder.add_conditional_edges("llm",tools_condition)
builder.add_edge("tools","image_search")
builder.add_edge("image_search","final_llm")
builder.add_edge("final_llm",END)



graph = builder.compile()
